/**
 * Module Federation runtime loader.
 *
 * Design goals:
 *   - URL-based dynamic remote module fetching (works in browser & Node).
 *   - Shared dependency registry so React / UI libs are loaded once
 *     across host + remotes (singleton, version-negotiated).
 *   - Framework-agnostic; integrates with Parcel via a virtual entry that
 *     imports `@boltpack/federation/runtime`.
 *
 * Two layers:
 *   1. Runtime (browser/Node): `federationRuntime` — injected into the host.
 *   2. Build-time helper (Node): `defineFederation` — produces a manifest
 *      consumed by the runtime.
 */

// ───────────────────────────────────────────────────────────────────────────
// Build-time: emit federation manifest from config
// ───────────────────────────────────────────────────────────────────────────

/**
 * Config shape (declared in boltpack.config.js):
 *   federation: {
 *     name: 'host',
 *     remotes: { app1: 'https://cdn.example.com/remote-app1/remoteEntry.js' },
 *     shared: {
 *       react: { singleton: true, requiredVersion: '^18.0.0' },
 *       'react-dom': { singleton: true },
 *     },
 *   }
 */
export function defineFederation(config) {
  if (!config || !config.name) {
    throw new Error('federation config requires a `name`');
  }
  return {
    name: config.name,
    exposes: config.exposes || {},
    remotes: config.remotes || {},
    shared: normalizeShared(config.shared || {}),
  };
}

function normalizeShared(shared) {
  const out = {};
  for (const [key, val] of Object.entries(shared)) {
    if (typeof val === 'string') {
      out[key] = { requiredVersion: val, singleton: false };
    } else {
      out[key] = {
        requiredVersion: val.requiredVersion || '*',
        singleton: val.singleton ?? false,
        eager: val.eager ?? false,
      };
    }
  }
  return out;
}

/**
 * Serialise the federation manifest to a JS snippet that bootstraps the runtime.
 * This file is emitted into the build output and imported by the host entry.
 */
export function buildRuntimeBootstrap(manifest) {
  return `// Auto-generated by boltpack federation. Do not edit.
import { federationRuntime } from '@boltpack/federation/runtime';
federationRuntime.init(${JSON.stringify(manifest, null, 2)});
export { federationRuntime };
`;
}

// ───────────────────────────────────────────────────────────────────────────
// Runtime: loaded inside the host app (browser) / SSR (Node)
// ───────────────────────────────────────────────────────────────────────────

const sharedRegistry = new Map();      // moduleName -> { instance, version, consumers }
const remoteCache = new Map();         // remoteUrl -> Promise<moduleExports>
const loadedRemotes = new Map();       // remoteName -> { url, scope }

function loadScript(url) {
  return new Promise((resolve, reject) => {
    // Browser: inject <script>. Node: dynamic import (http(s) URLs via fetch+eval skipped).
    if (typeof document !== 'undefined') {
      const el = document.createElement('script');
      el.src = url;
      el.type = 'module';
      el.onload = () => resolve();
      el.onerror = () => reject(new Error(`Failed to load remote: ${url}`));
      document.head.appendChild(el);
    } else {
      reject(new Error('Remote script loading requires a browser environment'));
    }
  });
}

/**
 * Register a shared module instance. Called by the host and every remote
 * the first time they initialise the module. Singleton negotiation: the
 * first registration wins when `singleton: true`.
 */
export function registerShared(name, version, instance, { singleton = false } = {}) {
  const existing = sharedRegistry.get(name);
  if (existing && singleton) {
    existing.consumers += 1;
    return existing.instance;
  }
  sharedRegistry.set(name, { instance, version, consumers: 1, singleton });
  return instance;
}

/**
 * Retrieve a shared module. If a singleton has been registered, return it;
 * otherwise return the locally-bundled fallback (the caller's own import).
 */
export function loadShared(name, localFallback) {
  const entry = sharedRegistry.get(name);
  if (entry && entry.singleton) return entry.instance;
  return localFallback;
}

/**
 * Dynamically load a remote module by URL + exposed module path.
 *   await loadRemote('app1', './Button')
 */
export async function loadRemote(remoteName, modulePath) {
  const remote = loadedRemotes.get(remoteName);
  if (!remote) throw new Error(`Remote "${remoteName}" not initialised`);

  const cacheKey = `${remote.url}::${modulePath}`;
  if (remoteCache.has(cacheKey)) return remoteCache.get(cacheKey);

  const promise = (async () => {
    await loadScript(remote.url);
    // Remote entry is expected to attach its exports to window[scope]
    const scope = window[remoteName];
    if (!scope || typeof scope.get !== 'function') {
      throw new Error(`Remote "${remoteName}" did not register a valid container`);
    }
    const factory = await scope.get(modulePath);
    const mod = factory();
    remoteCache.set(cacheKey, mod);
    return mod;
  })();

  remoteCache.set(cacheKey, promise);
  return promise;
}

/**
 * Public runtime facade. `init()` is called once at host bootstrap with the
 * federation manifest produced by `defineFederation` at build time.
 */
export const federationRuntime = {
  init(manifest) {
    for (const [name, url] of Object.entries(manifest.remotes)) {
      loadedRemotes.set(name, { url, scope: name });
    }
    // Shared modules register themselves lazily via registerShared() as
    // each chunk boots. Here we just record the singleton policy.
    for (const [name, cfg] of Object.entries(manifest.shared)) {
      if (cfg.singleton && !sharedRegistry.has(name)) {
        sharedRegistry.set(name, { instance: null, version: null, consumers: 0, singleton: true, pending: cfg });
      }
    }
  },
  loadRemote,
  loadShared,
  registerShared,
  __registry: sharedRegistry,
};
